/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    instruments: Instrument;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    instruments: InstrumentsSelect<false> | InstrumentsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'ro' | 'de' | 'fr' | 'nl' | 'ja' | 'ko' | 'el')
    | ('en' | 'ro' | 'de' | 'fr' | 'nl' | 'ja' | 'ko' | 'el')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ro' | 'de' | 'fr' | 'nl' | 'ja' | 'ko' | 'el';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Avatar URL from OAuth provider
   */
  image?: string | null;
  provider?: ('credentials' | 'google' | 'facebook' | 'apple') | null;
  /**
   * Unique ID from the OAuth provider
   */
  providerId?: string | null;
  roles?: ('admin' | 'user')[] | null;
  shippingAddress?: {
    street?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  phone?: string | null;
  /**
   * Multiple addresses for flexible shipping options
   */
  savedAddresses?:
    | {
        /**
         * e.g., Home, Work, Studio
         */
        label: string;
        street: string;
        apartment?: string | null;
        city: string;
        state: string;
        zip: string;
        country: string;
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruments".
 */
export interface Instrument {
  id: number;
  title: string;
  slug?: string | null;
  instrumentType: 'violin' | 'viola' | 'cello' | 'contrabass';
  /**
   * e.g., Stradivari, Guarneri, Montagnana
   */
  model?: string | null;
  status: 'available' | 'in-build' | 'reserved' | 'sold';
  /**
   * Price in EUR (€)
   */
  price: number;
  /**
   * Number of units in stock
   */
  stock: number;
  /**
   * Year crafted
   */
  year: number;
  /**
   * Detailed description of the instrument for product pages
   */
  luthierNotes?: string | null;
  mainImage: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Upload an audio demo (MP3 recommended)
   */
  audioSample?: (number | null) | Media;
  specs?: {
    bodyWood?: string | null;
    topWood?: string | null;
    neckWood?: string | null;
    fingerboardWood?: string | null;
    varnish?: string | null;
    strings?: string | null;
    /**
     * e.g., 356mm for violin, 755mm for cello
     */
    bodyLength?: string | null;
    /**
     * Vibrating string length (specific to double bass)
     */
    stringVibration?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  /**
   * Linked user account (if logged in during purchase)
   */
  customer?: (number | null) | User;
  /**
   * Email for guest checkouts
   */
  guestEmail?: string | null;
  status: 'pending_payment' | 'paid' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
  /**
   * How the customer will pay
   */
  paymentMethod?: ('bank_transfer' | 'cash' | 'card' | 'other') | null;
  /**
   * Bank transfer reference, transaction ID, or other payment identifier
   */
  paymentReference?: string | null;
  /**
   * How the customer will receive their instrument
   */
  deliveryMethod: 'delivery' | 'pickup';
  /**
   * Carrier tracking number
   */
  trackingNumber?: string | null;
  /**
   * Full tracking URL (optional)
   */
  trackingUrl?: string | null;
  /**
   * Estimated delivery date (e.g., "January 15-17, 2025")
   */
  estimatedDelivery?: string | null;
  /**
   * Scheduled pickup date/time (e.g., "January 15, 2025 at 10:00 AM")
   */
  pickupDate?: string | null;
  shippedAt?: string | null;
  items: {
    instrument: number | Instrument;
    /**
     * Snapshot of instrument title at time of purchase
     */
    title: string;
    /**
     * Price at time of purchase (EUR)
     */
    price: number;
    id?: string | null;
  }[];
  contactInfo: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
  };
  /**
   * Only required for delivery orders (not pickup)
   */
  shippingAddress?: {
    street?: string | null;
    apartment?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: string | null;
  };
  /**
   * Stripe PaymentIntent ID (empty for bank transfer orders)
   */
  paymentIntentId?: string | null;
  /**
   * Sum of item prices (EUR)
   */
  subtotal: number;
  /**
   * Shipping cost (EUR) - typically 0 as delivery is included in price
   */
  shipping: number;
  /**
   * Insurance cost (EUR) - typically 0 as insurance is included in price
   */
  insurance: number;
  /**
   * Total amount (EUR)
   */
  total: number;
  paidAt?: string | null;
  /**
   * Internal notes about the order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'instruments';
        value: number | Instrument;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  image?: T;
  provider?: T;
  providerId?: T;
  roles?: T;
  shippingAddress?:
    | T
    | {
        street?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  phone?: T;
  savedAddresses?:
    | T
    | {
        label?: T;
        street?: T;
        apartment?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
        isDefault?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "instruments_select".
 */
export interface InstrumentsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  instrumentType?: T;
  model?: T;
  status?: T;
  price?: T;
  stock?: T;
  year?: T;
  luthierNotes?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  audioSample?: T;
  specs?:
    | T
    | {
        bodyWood?: T;
        topWood?: T;
        neckWood?: T;
        fingerboardWood?: T;
        varnish?: T;
        strings?: T;
        bodyLength?: T;
        stringVibration?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  guestEmail?: T;
  status?: T;
  paymentMethod?: T;
  paymentReference?: T;
  deliveryMethod?: T;
  trackingNumber?: T;
  trackingUrl?: T;
  estimatedDelivery?: T;
  pickupDate?: T;
  shippedAt?: T;
  items?:
    | T
    | {
        instrument?: T;
        title?: T;
        price?: T;
        id?: T;
      };
  contactInfo?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        email?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        street?: T;
        apartment?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
      };
  paymentIntentId?: T;
  subtotal?: T;
  shipping?: T;
  insurance?: T;
  total?: T;
  paidAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}